apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: another-service
  description: A description of another service
  owner: ashwin-tide
  annotations:
    github.com/project-slug: helleu/repo2
    github.com/team-slug: helleu/testteam
    
  labels:
    project: repo2
    team: testteam
spec:
  type: service
  lifecycle: production
  owner: ashwin-tide
  dependsOn:
    - my-service
  providesApis: []
  consumesApis: 
    - my-service-api
